server{
    listen 443 ssl;    #listen for HTTPS traffic on port 443 and enable SSL/TLS.
    server_name hasserao.42.fr;   #the domain name that this server block should respond to.
    ssl_protocols TLSv1.3;
    ssl_certificate /etc/nginx/ssl/inception.crt;  #the path to the SSL/TLS certificate file.
    ssl_certificate_key /etc/nginx/ssl/inception.key;  #the path to the SSL/TLS private key file.

    root /usr/share/nginx/html;
    index index.html index.htm;
    #root /var/www/html;  #the root directory for the website files.
    #index index.php index.html index.htm;  #This tells NGINX to look for these files in order when serving a directory request.

    location ~\.php$ {    #matches any URI that ends with .php.
        try_files $uri =404;  #first try serving the requested file, and if it doesn't exist, return a 404 Not Found error.
       # include snippets/fastcgi-php.conf; #includes an external NGINX configuration file that likely contains the necessary FastCGI parameters for handling PHP requests.
        #fastcgi_pass wordpress:9000; # forward the PHP request to a FastCGI server running in a container named wordpress on port 9000.
    }
}