version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    expose:
      - 3306 #communication at same network
    restart: unless-stopped



  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    expose:
      - 9000
    depends_on:
      - mariadb
    restart: on-failure
  



  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    restart: unless-stopped

volumes:

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hasserao/Desktop/volumes/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hasserao/Desktop/volumes/mariadb



networks:
  inception:
    driver: bridge
