[www]  #pool name

user = www-data #user running the php process
group = www-data 
listen = my_wordpress:9000 #listen on port 9000 with hostname wordpress
listen.owner = www-data #owner of the socket
listen.group = www-data 
pm = dynamic #dynamic process manager to handle the load
pm.max_children = 5 #maximum number of children processes
pm.start_servers = 2 #number of children processes created on startup
pm.min_spare_servers = 1 #minimum number of idle processes to keep
pm.max_spare_servers = 3 #maximum number of idle processes to keep
clear_env = no #keep the environment variables from the paret process to the child process
